name: Build and Deploy
on:
  push:
    branches:
      - live
      - main
      - 'renovate/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        name: Setup NodeJS
        with:
          node-version: 18

      - uses: pnpm/action-setup@537643d491d20c2712d11533497cb47b2d0eb9d5 # tag=v2.2.3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.9.4
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3
        name: "Next JS Cache"
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build 
      - run: |           
            mkdir dist
            mkdir -p app/standalone/public
            cp ./package.json app
            cp -r .next/standalone app
            cp .next/static app/standalone/.next/ -r
            cp -r public/* app/standalone/public/
            cp ecosystem.config.js app
            tar -cJf dist/standalone-dist.tar.xz app
        name: Create artifact

      - name: Upload artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: nodejs-app
          path: ./dist/standalone-dist.tar.xz
          retention-days: 3
  deploy:
    needs: 'build'
    name: Deploy to server
    if: github.ref == 'refs/heads/live'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: nodejs-app

      - name: Copy artifact to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "standalone-dist.tar.xz"
          target: "/srv/http/pnf/"

      - name: Setup Node JS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            rm -rf app && tar --overwrite -xf standalone-dist.tar.xz
            cd app && pm2 restart ecosystem.config.js
      
